name: Lint Python Code

on: [push, pull_request]

jobs:
  lint:
    runs-on: ubuntu-latest
    steps:
      - name: Check out code
        uses: actions/checkout@v3  # 更新到 v3

      - name: Set up Python
        uses: actions/setup-python@v3  # 更新到 v3
        with:
          python-version: '3.12'  # 使用 Python 3.12

      - name: Install dependencies
        run: |
          python -m pip install --upgrade pip
          pip install pylint
          pip install -r requirements.txt  # 安装项目依赖

      - name: Run Pylint
        run: |
          pylint app/  # 指定代码目录为 app
